name = "graphql-yoga-example"

account_id = ""
workers_dev = true

compatibility_date = "2021-11-15"
compatibility_flags = ["streams_enable_constructors"]

main = "./dist/index.mjs"

[build]
command = "npm run build"
